@baseUrl = http://localhost:3000



### Create a place

### ajoutLieux
POST {{baseUrl}}/vacances/ajoutLieu
Content-Type: application/json

{
    "lieu":"lion",
    "description":"LA belle vie"
}

### Create a user
### ajoutLieux
POST {{baseUrl}}/users/ajout
Content-Type: application/json

{
    "nom":"ui",
    "email":"emailhhbkjaziq"
}

### Like a place
### ajoutLieux
POST {{baseUrl}}/favoris/ajoutFavori
Content-Type: application/json

{
    "idUtilisateur":"6",
    "idLieu":"6"
}

